Updated Agreement Categories
tractusx-team-portal-onboarding/devenv pull request #8
Opened 2022-04-12 18:47 UTC by jjeroch

2022-04-12 18:49 UTC, jjeroch commented
@wira-mms can you please check if the added foreign key table link is set correctly?

2022-04-19 17:29 UTC, ntruchsess requested changes
I did go through all changes and instead of adding a ton of comments I fixed all errors (space/tab etc...) in new PR https://github.com/tractusx-team-portal-onboarding/devenv/pull/14
(That PR will also resolve the conflicts that this PR does have)

2022-04-21 07:01 UTC, jjeroch commented
@wira-mms  also ok to merge? :)

2022-04-21 09:47 UTC, wira-mms approved these changes

2022-04-21 10:44 UTC, merged